### ISSUE TITLE
module isnt working even afterinstall is complete

### ISSUE THREAD

**Issue by acevedoa9805** [pimoroni/pantilt-hat#11]
`Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pantilthat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pantilthat/__init__.py", line 15, in <module>
    pantilthat = PanTilt(i2c_bus=SMBus(1))
  File "/usr/local/lib/python2.7/dist-packages/pantilthat/pantilt.py", line 63, in __init__
    self._set_config()
  File "/usr/local/lib/python2.7/dist-packages/pantilthat/pantilt.py", line 100, in _set_config
    self._i2c_write_byte(self.REG_CONFIG, config)
  File "/usr/local/lib/python2.7/dist-packages/pantilthat/pantilt.py", line 191, in _i2c_write_byte
    raise IOError("Failed to write byte")
IOError: Failed to write byte
>>> import pantilt-hat
  File "<stdin>", line 1
    import pantilt-hat
                  ^
SyntaxError: invalid syntax
`

Those are the erros the i am facing if anybody could please help

**Comment by Gadgetoid** [comment]
`import pantilthat` is correct, but it looks like it's failing to communicate with the HAT. Is it plugged securely on your Pi? What sort of Pi/header are you using?
