### ISSUE TITLE
Upgrade from rPi3 to rPi4 no more movement

### ISSUE THREAD

**Issue by prutsky** [pimoroni/pantilt-hat#24]
Hi,
I used my pan tilt HAT with great succes on my Raspberry Pi 3B+ bur now I moved to a Pi 4 and somehow the pan tilt HAT won't respond anymore. When I plu in the power to the Pi, the servos do move some bit. I installed the pan tilt software. When I want to test an example I get the following error:
> python timeout.py 
Traceback (most recent call last):
  File "timeout.py", line 10, in <module>
    pantilthat.pan(-90)
  File "/usr/lib/python3/dist-packages/pantilthat/pantilt.py", line 466, in servo_one
    self.setup()
  File "/usr/lib/python3/dist-packages/pantilthat/pantilt.py", line 80, in setup
    self._set_config()
  File "/usr/lib/python3/dist-packages/pantilthat/pantilt.py", line 118, in _set_config
    self._i2c_write_byte(self.REG_CONFIG, config)
  File "/usr/lib/python3/dist-packages/pantilthat/pantilt.py", line 209, in _i2c_write_byte
    raise IOError("Failed to write byte")
OSError: Failed to write byte

What goes wrong here?

**Comment by prutsky** [comment]
I see this issue also on the Pimoroni support forum now. Closing it.
