### ISSUE TITLE
raise IOError("Failed to read byte")

### ISSUE THREAD

**Issue by peterss7** [pimoroni/pantilt-hat#29]
I have the Pimoroni pantilt hat attached to a raspberry pi 4 8gb with the neopixel stick. In the program I am working on, I use Tensorflow and Opencv to track objects. The program works, but within minutes of starting I get the error: 

OSError: failed to write byte

Earlier in the message that is spit out when the program crashes, it says "failure to read byte."  I believe it has something to do with i2c, even though I am not using i2c in my code or set up. I can provide more information, I'm just not sure what more is relevant.

**Comment by druck13** [comment]
It's all done with i2c, have a look in library/pantilthat/pantilt.py

**Comment by Gadgetoid** [comment]
This could be a power fluctuation or intermittent wiring issue causing i2c communications with the driver chip on PanTilt HAT to be unstable. How is your setup wired/powered?

It could equally be some quirk of the code you're driving it with since threaded code- for example- can cause issues with i2c transactions clobbering each other.

**Comment by peterss7** [comment]
> This could be a power fluctuation or intermittent wiring issue causing i2c communications with the driver chip on PanTilt HAT to be unstable. How is your setup wired/powered?
> 
> It could equally be some quirk of the code you're driving it with since threaded code- for example- can cause issues with i2c transactions clobbering each other.

......
I think it was the code.  I made a change that took a little load off of the hat and now it's working exactly like it's supposed to without crashing.

**Comment by Sreehar** [comment]
> 

Hey, can you tell how you got it working in detail.
I too am facing the same problem.
Traceback (most recent call last):
File "/home/pi/track/facetracker.py", line 37, in
pan(cam_pan-90)
File "/usr/lib/python3/dist-packages/pantilthat/pantilt.py", line 466, in servo_one
self.setup()
File "/usr/lib/python3/dist-packages/pantilthat/pantilt.py", line 80, in setup
self._set_config()
File "/usr/lib/python3/dist-packages/pantilthat/pantilt.py", line 118, in _set_config
self._i2c_write_byte(self.REG_CONFIG, config)
File "/usr/lib/python3/dist-packages/pantilthat/pantilt.py", line 209, in _i2c_write_byte
raise IOError("Failed to write byte")
OSError: Failed to write byte

**Comment by chucknitro** [comment]
Same here.  Anyone help?

**Comment by Sreehar** [comment]
> Same here. Anyone help?

![images](https://user-images.githubusercontent.com/48317799/227114968-5d70fd47-d3a2-423e-8e97-afd326987a02.jpeg)
Are you using this board exactly?
Or this 
![images (1)](https://user-images.githubusercontent.com/48317799/227115075-05ab71f8-be34-4ce4-81ba-7eaffbc98719.jpeg)

**Comment by chucknitro** [comment]
I think I found it.  The cable underneath the hat shorts out on the heatsink.  Added static paper and it all worked :)

Give that a try.

**Comment by Julian-bt** [comment]
> > Same here. Anyone help?
> 
> ![images](https://user-images.githubusercontent.com/48317799/227114968-5d70fd47-d3a2-423e-8e97-afd326987a02.jpeg) Are you using this board exactly? Or this ![images (1)](https://user-images.githubusercontent.com/48317799/227115075-05ab71f8-be34-4ce4-81ba-7eaffbc98719.jpeg)

Did you find the issue ?
I have the same problem...

**Comment by thirdr** [comment]
Closed as resolved.
